[makejinja]
inputs = ["./template/overrides","./template/config"]
output = "./"
exclude_patterns = ["*.partial.yaml.jinja"]
data = ["./cluster.toml"]
import_paths = ["./template/scripts"]
loaders = ["plugin:Plugin"]
jinja_suffix = ".jinja"
copy_metadata = true
force = true
undefined = "strict"

[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "#|"
comment_end = "#|"
variable_start = "#{"
variable_end = "}#"
